version: '3.4'

services:
  integrationtest:
    image: ${DOCKER_REGISTRY-}integrationtest
    build:
      context: .
      dockerfile: IntegrationTest/Dockerfile
    networks:
        - redis-network
        - rabbitmq-network
  rabbitmq3:
    image: rabbitmq:3-management
    environment: 
        RABBITMQ_ERLANG_COOKIE: 'just-for-study-do-not-use-it-in-production'
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    volumes:
        - ./IntegrationTest/App_Data/rabbitmq-data:/var/lib/rabbitmq
    ports:
        - 15672:15672
        - 5672:5672
    networks: 
        - rabbitmq-network 
  redis:
    image: redis
    restart: unless-stopped
    ports:
        - "6379:6379"
    networks: 
        - redis-network 
networks:
    redis-network:
        driver: bridge
    rabbitmq-network:
        driver: bridge

